FROM golang:latest as dev

ENV VERSION=7.1.0
RUN curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/$VERSION/hurl_${VERSION}_amd64.deb && \
    apt update && \
    apt install -y ./hurl_${VERSION}_amd64.deb

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Project-scoped install of air
RUN go get -tool github.com/air-verse/air@latest

COPY . .

EXPOSE 8080

# Use the air tool installed via go get -tool
CMD ["go", "tool", "air"]

